import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
	mainScroll: {
		backgroundColor: 'rgba(60, 176, 157, 0.1)',
	},
	mainBlock: {
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	picture: {
		height: 90,
		width: 90,
		borderRadius: 45,
	},
	cardContainer: {
		width: 250,
		alignItems: 'center',
		justifyContent: 'center',
		marginVertical: 20,
		borderRadius: 5,
		backgroundColor: 'white',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 3,
		},
		shadowOpacity: 0.27,
		shadowRadius: 4.65,
		elevation: 6,
	},
	addCardContainer: {
		width: 300,
		marginTop: 20,
		marginBottom: 40,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 5,
		backgroundColor: 'white',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 3,
		},
		shadowOpacity: 0.27,
		shadowRadius: 4.65,
		elevation: 6,
	},
	wrapper: {
		width: '85%',
		marginVertical: 10,
	},
	myPetPhoto: {
		marginTop: 30,
		alignItems: 'center',
	},
	myPetPhotoText: {
		marginTop: 5,
		marginLeft: 10,
		fontSize: 20,
		color: 'black',
	},
	pointContainer: {
		justifyContent: 'space-between',
		flexDirection: 'row',
		marginVertical: 5,
	},
	pointText: {
		fontSize: 14,
		color: 'black',
	},
	addPetContainer: {
		alignItems: 'center',
		justifyContent: 'center',
		marginVertical: 130,
	},
	addPetButton: {
		width: 150,
		height: 150,
		borderRadius: 75,
		backgroundColor: '#E9EAFF',
		borderWidth: 2,
		borderStyle: 'dotted',
		borderColor: '#5D5FEF',
		alignItems: 'center',
		justifyContent: 'center',
	},
	addPetIcon: {
		color: '#5D5FEF',
	},
	addPetText: {
		marginTop: 20,
		fontSize: 20,
		color: 'black',
	},
	individualNoticeInput: {
		color: 'black',
	},
	nickNameBlock: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	cardContainer: {
		width: 300,
		alignItems: 'center',
		justifyContent: 'center',
		marginVertical: 20,
		borderRadius: 5,
		backgroundColor: 'white',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 3,
		},
		shadowOpacity: 0.27,
		shadowRadius: 4.65,
		elevation: 6,
	},
	arrowContainer: {
		alignItems: 'flex-end',
	},
	modalContainer: {
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(187, 187, 187, 0.5)',
	},
	modalWrapper: {
		backgroundColor: 'red',
		width: 300,
		marginTop: 20,
		marginBottom: 40,
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 5,
		backgroundColor: 'rgba(255, 255, 255, 1)',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 3,
		},
		shadowOpacity: 0.27,
		shadowRadius: 4.65,
		elevation: 6,
	},
	titleText: {
		textAlign: 'center',
		fontSize: 16,
		color: 'black',
		marginTop: 20,
	},
	acceptButton: {
		shadowOffset: {
			width: 0,
			height: 3,
		},
		shadowOpacity: 0.27,
		shadowRadius: 4.65,
		elevation: 6,
		borderWidth: 2,
		borderColor: '#a8abfd',
		paddingVertical: 5,
		paddingHorizontal: 25,
		borderRadius: 5,
		backgroundColor: 'white',
		marginVertical: 20,
	},
	acceptText: {
		color: '#a8abfd',
	},
	pointContainer: {
		justifyContent: 'space-between',
		flexDirection: 'row',
		marginVertical: 5,
	},
	pointText: {
		fontSize: 14,
		color: 'black',
	},
})
